images:
  - build
  - doxygen
  - freecad
  - gnu-arm-embedded-toolchain
  - gnuradio
  - jupyter-octave
  - mea-cia3
  - mea-project-s8
  - my-jupyter
  - my-latex
  - riscv-dev
  - riscv-gnu-toolchain
  - stm32-dev
#  - wine
