name: build
'on':
  push:
    branches:
    - main
  schedule:
  - cron: 0 0 1 * *
jobs:
  gcc-arm-none-eabi:
    name: gcc-arm-none-eabi
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push image
      run: 'GIT_HASH=$(git rev-parse --short HEAD)

        docker buildx build           --cache-from type=local,src=/tmp/.buildx-cache           --cache-to
        type=local,dest=/tmp/.buildx-cache           --push           -t ${DOCKERHUB_USERNAME}/gcc-arm-none-eabi:10.3-2021.10           -t
        ${DOCKERHUB_USERNAME}/gcc-arm-none-eabi:${GIT_HASH}-10.3-2021.10           ./gcc-arm-none-eabi

        '
  stm32-dev:
    name: stm32-dev
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push image
      run: 'GIT_HASH=$(git rev-parse --short HEAD)

        docker buildx build           --cache-from type=local,src=/tmp/.buildx-cache           --cache-to
        type=local,dest=/tmp/.buildx-cache           --push           -t ${DOCKERHUB_USERNAME}/stm32-dev:latest           -t
        ${DOCKERHUB_USERNAME}/stm32-dev:${GIT_HASH}-latest           ./stm32-dev

        '
    needs:
    - gcc-arm-none-eabi
