name: build
'on':
  push:
    branches:
    - main
  schedule:
  - cron: 0 0 1 * *
jobs:
  gcc-arm-none-eabi-10-3-2021-10:
    name: gcc-arm-none-eabi-10-3-2021-10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-gcc-arm-none-eabi-10-3-2021-10
        cache-to: type=gha,mode=max,scope=build-gcc-arm-none-eabi-10-3-2021-10
        context: gcc-arm-none-eabi
        tags: alencarfelipe/gcc-arm-none-eabi:10.3-2021.10, alencarfelipe/gcc-arm-none-eabi:latest
        build-args: VERSION=10.3-2021.10
  gcc-arm-none-eabi-9-2019-q4-major:
    name: gcc-arm-none-eabi-9-2019-q4-major
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-gcc-arm-none-eabi-9-2019-q4-major
        cache-to: type=gha,mode=max,scope=build-gcc-arm-none-eabi-9-2019-q4-major
        context: gcc-arm-none-eabi
        tags: alencarfelipe/gcc-arm-none-eabi:9-2019-q4-major
        build-args: 'VERSION=9-2019-q4-major

          URL=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2'
  libgemmini-latest:
    name: libgemmini-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-libgemmini-latest
        cache-to: type=gha,mode=max,scope=build-libgemmini-latest
        context: libgemmini
        tags: alencarfelipe/libgemmini:latest
        build-args: ''
    needs:
    - riscv-dev-latest
  nrf5-dev-latest:
    name: nrf5-dev-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-nrf5-dev-latest
        cache-to: type=gha,mode=max,scope=build-nrf5-dev-latest
        context: nrf5-dev
        tags: alencarfelipe/nrf5-dev:latest
        build-args: ''
    needs:
    - gcc-arm-none-eabi-9-2019-q4-major
  riscv-dev-latest:
    name: riscv-dev-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-riscv-dev-latest
        cache-to: type=gha,mode=max,scope=build-riscv-dev-latest
        context: riscv-dev
        tags: alencarfelipe/riscv-dev:latest
        build-args: ''
    needs:
    - riscv-gnu-toolchain-e65e7fc
  riscv-gnu-toolchain-e65e7fc:
    name: riscv-gnu-toolchain-e65e7fc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-riscv-gnu-toolchain-e65e7fc
        cache-to: type=gha,mode=max,scope=build-riscv-gnu-toolchain-e65e7fc
        context: riscv-gnu-toolchain
        tags: alencarfelipe/riscv-gnu-toolchain:e65e7fc, alencarfelipe/riscv-gnu-toolchain:latest
        build-args: VERSION=e65e7fc
  stm32-dev-latest:
    name: stm32-dev-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha,scope=build-stm32-dev-latest
        cache-to: type=gha,mode=max,scope=build-stm32-dev-latest
        context: stm32-dev
        tags: alencarfelipe/stm32-dev:latest
        build-args: ''
    needs:
    - gcc-arm-none-eabi-10-3-2021-10
