name: build
'on':
  push:
    branches:
    - main
  schedule:
  - cron: 0 0 1 * *
jobs:
  gcc-arm-none-eabi-10-3-2021-10:
    name: gcc-arm-none-eabi-10-3-2021-10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/gcc-arm-none-eabi:10.3-2021.10
  gcc-arm-none-eabi-9-2019-q4-major:
    name: gcc-arm-none-eabi-9-2019-q4-major
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/gcc-arm-none-eabi:9-2019-q4-major
  libgemmini-latest:
    name: libgemmini-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/libgemmini:latest
    needs:
    - riscv-dev-latest
  nrf5-dev-latest:
    name: nrf5-dev-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/nrf5-dev:latest
    needs:
    - gcc-arm-none-eabi-9-2019-q4-major
  riscv-dev-latest:
    name: riscv-dev-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/riscv-dev:latest
    needs:
    - riscv-gnu-toolchain-e65e7fc
  riscv-gnu-toolchain-e65e7fc:
    name: riscv-gnu-toolchain-e65e7fc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/riscv-gnu-toolchain:e65e7fc
  stm32-dev-latest:
    name: stm32-dev-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      run: ./build.py --push --update-cache alencarfelipe/stm32-dev:latest
    needs:
    - gcc-arm-none-eabi-10-3-2021-10
