name: CI
on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 0 1 * *"

jobs:
  CI:
    runs-on: ubuntu-latest
    container: 
      image: alencarfelipe/build
      env:
        PUSH_EN: "True"
        HUB_USER: alencarfelipe
        HUB_PASS: ${{ secrets.HUB_PASS }}
        IMAGES_PATH: /__w/docker-images/docker-images

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Build Images
        run: pwd && python /app/main.py